name         'smarchive-virtualbox'
version      '0.2.3'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/smarchive/puppet-virtualbox'
source       'https://github.com/smarchive/puppet-virtualbox'
summary      'Puppet module to install Oracle VirtualBox from the official Oracle Linux repository'
description  'A Puppet module to install VirtualBox from the official Oracle Linux repository.'
dependency   'puppetlabs/apt', '>= 1.0.0'
